[package]
name = "nodium"
version = "0.1.2"
authors = ["cherob"]
description = "Nodium is an easy-to-use data analysis and automation platform built using Rust, designed to be versatile and modular. Nodium aims to provide a user-friendly visual node-based interface for various tasks."
edition = "2021"
license = "AGPL-3.0"

[dependencies]
shaku = "0.5"
tokio = { version = "1.0", features = ["full"] }
eframe = "0.15.0"

log = "0.4"
env_logger = "0.9"

nodium-core = { path = "libs/core" }
nodium-app = { path = "libs/app" }
nodium-events = { path = "libs/events" }