[package]
name = "nodium"
version = "0.1.1"
authors = ["cherob"]
description = "Nodium is an easy-to-use data analysis and automation platform using Rust with a visual node-based interface. It includes a plugin browser for downloading extensions, making it versatile for a wide range of data manipulation tasks. No coding experience required."
edition = "2021"
license = "AGPL-3.0"

[dependencies]
notime = { path = "libs/notime" }
nodium_egui = { path = "libs/nodium_egui" }

tokio = { version = "1.0", features = ["full"] }

eframe = "0.15.0"