[package]
name = "nodium"
version = "0.1.2"
authors = ["cherob"]
description = "Nodium is an easy-to-use data analysis and automation platform built using Rust, designed to be versatile and modular. Nodium aims to provide a user-friendly visual node-based interface for various tasks."
edition = "2021"
license-file = "LICENSE"

[dependencies]
nodium-plugins = { path = "libs/plugins", version = "0.1.1" }
nodium-app = { path = "libs/app", version = "0.1.1" }
nodium-events = { path = "libs/events", version = "0.1.2" }
nodium-pdk = { path = "libs/pdk", version = "0.1.1" }
log = "0.4"
env_logger = "0.9"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"

tokio = { version = "1.27.0", features = ["full"] }

[dependencies.nodium-egui]
path = "libs/view/egui"
version = "0.1.0"
optional = true

[dependencies.nodium-tauri]
path = "libs/view/tauri"
version = "0.1.0"
optional = true

[dependencies.nodium-console]
path = "libs/view/console"
version = "0.1.0"
optional = true

[features]
default = ["nodium-console"]
egui = ["nodium-egui"]
tauri = ["nodium-tauri"]
console = ["nodium-console"]

# [build]
# rustflags = ["-A", "warnings"]