[package]
name = "nodium_extension_http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nodium_io = { path = "../lib/nodium_io" }
reqwest = "0.11.4"