[package]
name = "nodium_browser"
version = "0.1.0"
authors = ["cherob"]
description = "Provides a browser for the Nodium PDK"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
nodium-pdk = { version = "0.1.0" }

[lib]
name = "nodium_input"
crate-type = ["cdylib"]